### ISSUE TITLE
main(): issue

### ISSUE THREAD

**Issue by alimkoca** [realsuayip/zeynep#4]
That's pip3 installation:
```
alimk@pardus:~/Yazılım/zeynep$ pip3 install -r requirements.txt
Collecting Django==4.0.1
  Downloading Django-4.0.1-py3-none-any.whl (8.0 MB)
     |████████████████████████████████| 8.0 MB 1.9 MB/s 
Collecting psycopg2-binary==2.9.3
  Downloading psycopg2_binary-2.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 2.0 MB/s 
Collecting redis==4.1.0
  Downloading redis-4.1.0-py3-none-any.whl (171 kB)
     |████████████████████████████████| 171 kB 1.7 MB/s 
Collecting hiredis==2.0.0
  Downloading hiredis-2.0.0-cp39-cp39-manylinux2010_x86_64.whl (85 kB)
     |████████████████████████████████| 85 kB 541 kB/s 
Collecting djangorestframework==3.13.1
  Downloading djangorestframework-3.13.1-py3-none-any.whl (958 kB)
     |████████████████████████████████| 958 kB 1.7 MB/s 
Collecting drf-spectacular==0.21.2
  Downloading drf_spectacular-0.21.2-py3-none-any.whl (80 kB)
     |████████████████████████████████| 80 kB 1.2 MB/s 
Collecting factory-boy==3.2.1
  Downloading factory_boy-3.2.1-py2.py3-none-any.whl (35 kB)
Requirement already satisfied: asgiref<4,>=3.4.1 in /home/alimk/.local/lib/python3.9/site-packages (from Django==4.0.1->-r requirements.txt (line 1)) (3.5.0)
Requirement already satisfied: sqlparse>=0.2.2 in /home/alimk/.local/lib/python3.9/site-packages (from Django==4.0.1->-r requirements.txt (line 1)) (0.4.2)
Collecting pytz
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 2.3 MB/s 
Collecting inflection>=0.3.1
  Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting uritemplate>=2.0.0
  Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
Collecting jsonschema>=2.6.0
  Downloading jsonschema-4.4.0-py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 177 kB/s 
Requirement already satisfied: PyYAML>=5.1 in /usr/lib/python3/dist-packages (from drf-spectacular==0.21.2->-r requirements.txt (line 6)) (5.3.1)
Collecting Faker>=0.7.0
  Downloading Faker-13.3.3-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 1.7 MB/s 
Collecting deprecated>=1.2.3
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting packaging>=21.3
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 613 kB/s 
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.14.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
     |████████████████████████████████| 77 kB 722 kB/s 
Requirement already satisfied: python-dateutil>=2.4 in /usr/lib/python3/dist-packages (from Faker>=0.7.0->factory-boy==3.2.1->-r requirements.txt (line 7)) (2.8.1)
Collecting attrs>=17.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 780 kB/s 
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (115 kB)
     |████████████████████████████████| 115 kB 1.7 MB/s 
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging>=21.3->redis==4.1.0->-r requirements.txt (line 3)) (2.4.7)
Installing collected packages: wrapt, pytz, pyrsistent, Django, attrs, uritemplate, packaging, jsonschema, inflection, Faker, djangorestframework, deprecated, redis, psycopg2-binary, hiredis, factory-boy, drf-spectacular
  Attempting uninstall: Django
    Found existing installation: Django 4.0.3
    Uninstalling Django-4.0.3:
      Successfully uninstalled Django-4.0.3
  WARNING: The script django-admin is installed in '/home/alimk/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jsonschema is installed in '/home/alimk/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script faker is installed in '/home/alimk/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Django-4.0.1 Faker-13.3.3 attrs-21.4.0 deprecated-1.2.13 djangorestframework-3.13.1 drf-spectacular-0.21.2 factory-boy-3.2.1 hiredis-2.0.0 inflection-0.5.1 jsonschema-4.4.0 packaging-21.3 psycopg2-binary-2.9.3 pyrsistent-0.18.1 pytz-2022.1 redis-4.1.0 uritemplate-4.1.1 wrapt-1.14.0
```
And here is main error:
```
alimk@pardus:~/Yazılım/zeynep$ python3 manage.py runserver
Traceback (most recent call last):
  File "/home/alimk/Yazılım/zeynep/manage.py", line 21, in <module>
    main()
  File "/home/alimk/Yazılım/zeynep/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/alimk/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/alimk/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 369, in execute
    settings.INSTALLED_APPS
  File "/home/alimk/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 84, in __getattr__
    self._setup(name)
  File "/home/alimk/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 71, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/alimk/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 179, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/alimk/Yazılım/zeynep/zeynep/settings/__init__.py", line 2, in <module>
    from .apps import *
  File "/home/alimk/Yazılım/zeynep/zeynep/settings/apps.py", line 1, in <module>
    from zeynep.utils.envparse import env
  File "/home/alimk/Yazılım/zeynep/zeynep/utils/envparse.py", line 7, in <module>
    class EnvironmentParser:
  File "/home/alimk/Yazılım/zeynep/zeynep/utils/envparse.py", line 41, in EnvironmentParser
    str = _construct(str)
TypeError: 'staticmethod' object is not callable
```

**Comment by alimkoca** [comment]
I'm not sure but may be error based on Pardus 21 and it's software applications.

**Comment by realsuayip** [comment]
You need Python 3.10+

Besides, please user docker setup to run the project.
